apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: omatthew
  labels:
    app: db
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0  
  minReadySeconds: 20
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - envFrom:
         - secretRef:
             name: db-secret      
        name: db-deployment
        image: harbor.dev.afsmtddso.com/omatthew-harbor-project/db:49d0fd3-a1d0f4c
        ports:
        - containerPort: 5432
